# Backend configuration for NX Greenergy Project
# This file is used for GitHub auto-deployment with Dokploy

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/greenergy-app/greenergy-backend/Dockerfile
    container_name: greenergy-backend
    restart: always
    environment:
      # These environment variables should be configured in Dokploy admin
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1w}
    networks:
      - dokploy-network
    # External dependency - assumes postgres service is already running
    # No direct depends_on since services are deployed separately
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN:-example.com}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3333"
      - "traefik.http.middlewares.backend-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-strip@docker"
      - "dokploy.deploy.order=2" # Deploy backend after database

networks:
  dokploy-network:
    external: true # This network will be created by Dokploy
