version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: greenergy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenergy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - greenergy-network

networks:
  greenergy-network:
    driver: bridge

volumes:
  postgres_data:
